apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  strategy: {}
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: malefstorm1994/demoapp:8c635611ebbcd5c8873607008de66d1bf7130fb6
        name: demoapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
