name: CI
on: push
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: actions/login-action@v3
        with:
          registry: ghcr.io
          userame: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: actions/metadata-action@v5
        with:
          images: ghcr.io/{{ github.repository}}
