name: CI
on: push
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: malefstorm1994
          password: ViVa1994@WS


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./k8s/app
          push: true
          tags: malefstorm1994/k8sapp:latest